apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: console-web-dev
images:
  - name: console-api
    newName: ghcr.io/kriipke/console-api
    newTag: develop
  - name: console-web
    newName: ghcr.io/kriipke/console-web
    newTag: develop
resources:
  - ../../base
patches:
  - path: deployment.yaml
namePrefix: gitops-
namespace: console-dev
