---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-web
  namespace: console
spec:
  replicas: 3
  selector:
    matchLabels:
      app: console-web
  template:
    metadata:
      labels:
        app: console-web
    spec:
      containers:
        - name: console-web
          envFrom:
          - configMapRef:
              name: console-web-env
          image: ghcr.io/kriipke/console-web:develop
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: http
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
