apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: console-web-base

patchesStrategicMerge:
- patch.yaml

namespace: console-dev

images:
- name: console-api
  newName: ghcr.io/kriipke/console-api
  newTag: develop
- name: console-web
  newName: ghcr.io/kriipke/console-web
  newTag: develop

resources:
- deployment.yaml
- host.yaml
- kustomization.yaml
- listener-http.yaml
- listener-https.yaml
- mapping.yaml
- pod-autoscaler.yaml
- service.yaml
- tlscontext.yaml
